@extends('layouts.app')
@section('title', 'AI Reports')

@section('content')
<div class="space-y-5">

    {{-- Header --}}
    <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
            <h1 class="text-2xl font-semibold text-gray-900 dark:text-white">AI Reports</h1>
            <p class="text-sm text-gray-500 dark:text-gray-400 mt-0.5">Intelligence summaries for projects and clients — generated by AI, reviewed by you.</p>
        </div>
        <div class="flex items-center gap-3">
            <div class="rounded-xl bg-brand-50 dark:bg-brand-500/10 px-3 py-2 flex items-center gap-2">
                <div class="size-2 rounded-full bg-brand-500 animate-pulse"></div>
                <span class="text-xs font-medium text-brand-700 dark:text-brand-300">{{ $stats['total'] }} reports · {{ $stats['visible_client'] }} client-visible</span>
            </div>
        </div>
    </div>

    @if($summaries->isEmpty())
    <div class="rounded-2xl border border-dashed border-gray-200 bg-white p-16 text-center dark:border-gray-700 dark:bg-gray-900">
        <div class="mx-auto size-16 rounded-2xl bg-brand-50 dark:bg-brand-500/10 flex items-center justify-center mb-4">
            <svg class="size-8 text-brand-400" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"/></svg>
        </div>
        <h3 class="font-semibold text-gray-900 dark:text-white mb-1">No AI reports yet</h3>
        <p class="text-sm text-gray-500 dark:text-gray-400 max-w-sm mx-auto">Open a project or client profile to generate your first AI summary.</p>
        <div class="flex items-center justify-center gap-3 mt-4">
            <a href="{{ route('agency.projects.index') }}" class="rounded-lg bg-brand-500 px-4 py-2 text-sm font-medium text-white hover:bg-brand-600">Go to Projects</a>
            <a href="{{ route('agency.clients.index') }}" class="rounded-lg border border-gray-200 dark:border-gray-700 px-4 py-2 text-sm font-medium text-gray-600 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-800">Go to Clients</a>
        </div>
    </div>
    @else

    <div class="space-y-4">
        @foreach($summaries as $summary)
        @php
            $entity = $summary->summarizable;
            $entityName = $entity->name ?? $entity->title ?? 'Unknown';
            $isProject = $entity instanceof \App\Models\Project;
            $isClient  = $entity instanceof \App\Models\Client;
            $entityRoute = $isProject
                ? route('agency.projects.show', $entity)
                : ($isClient ? route('agency.clients.show', $entity) : null);
            $typeLabel = match($summary->type) {
                'project_summary' => 'Project',
                'client_summary'  => 'Client',
                default => ucwords(str_replace('_', ' ', $summary->type)),
            };
            $confidence = $summary->confidence ? round($summary->confidence * 100) : null;
            $confColor  = $confidence >= 80 ? 'success' : ($confidence >= 60 ? 'warning' : 'gray');
        @endphp

        <div class="rounded-2xl border border-gray-200 bg-white dark:border-gray-800 dark:bg-gray-900 overflow-hidden">
            {{-- Top accent bar --}}
            <div class="h-1 bg-gradient-to-r from-brand-400 via-brand-500 to-brand-600"></div>

            <div class="p-5">
                {{-- Header row --}}
                <div class="flex items-start justify-between gap-4 mb-4">
                    <div class="flex items-center gap-2.5 flex-wrap">
                        <span class="inline-flex items-center gap-1 rounded-full bg-brand-50 dark:bg-brand-500/10 px-2.5 py-1 text-xs font-semibold text-brand-700 dark:text-brand-300">
                            <svg class="size-3" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"/></svg>
                            {{ $typeLabel }}
                        </span>
                        @if($entityRoute)
                        <a href="{{ $entityRoute }}" class="text-sm font-semibold text-gray-900 dark:text-white hover:text-brand-500 transition-colors">
                            {{ $entityName }}
                        </a>
                        @else
                        <span class="text-sm font-semibold text-gray-900 dark:text-white">{{ $entityName }}</span>
                        @endif
                        @if($summary->subject)
                        <span class="text-xs text-gray-400">· {{ $summary->subject }}</span>
                        @endif
                    </div>
                    <div class="flex items-center gap-2 flex-shrink-0">
                        @if($summary->visible_to_client)
                        <span class="inline-flex items-center gap-1 rounded-full bg-success-50 dark:bg-success-500/10 px-2 py-0.5 text-xs font-medium text-success-700 dark:text-success-400">
                            <svg class="size-3" fill="currentColor" viewBox="0 0 20 20"><path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd"/></svg>
                            Client visible
                        </span>
                        @endif
                        @if($entityRoute)
                        <a href="{{ $entityRoute }}" class="text-xs text-brand-500 hover:text-brand-600 font-medium">View {{ $typeLabel }} →</a>
                        @endif
                        <span class="text-xs text-gray-400">{{ $summary->created_at->diffForHumans() }}</span>
                    </div>
                </div>

                {{-- Main content --}}
                <p class="text-sm text-gray-700 dark:text-gray-300 leading-relaxed mb-4">{{ $summary->content }}</p>

                {{-- Three-panel breakdown --}}
                @if($summary->what_happened || $summary->why || $summary->what_next)
                <div class="grid grid-cols-1 sm:grid-cols-3 gap-3 mb-4">
                    @if($summary->what_happened)
                    <div class="rounded-xl bg-blue-50 dark:bg-blue-500/5 border border-blue-100 dark:border-blue-800/30 p-3.5">
                        <div class="flex items-center gap-1.5 mb-1.5">
                            <div class="size-1.5 rounded-full bg-blue-400"></div>
                            <p class="text-xs font-semibold text-blue-700 dark:text-blue-300 uppercase tracking-wide">What Happened</p>
                        </div>
                        <p class="text-xs text-blue-600 dark:text-blue-400 leading-relaxed">{{ $summary->what_happened }}</p>
                    </div>
                    @endif
                    @if($summary->why)
                    <div class="rounded-xl bg-amber-50 dark:bg-amber-500/5 border border-amber-100 dark:border-amber-800/30 p-3.5">
                        <div class="flex items-center gap-1.5 mb-1.5">
                            <div class="size-1.5 rounded-full bg-amber-400"></div>
                            <p class="text-xs font-semibold text-amber-700 dark:text-amber-300 uppercase tracking-wide">Why It Matters</p>
                        </div>
                        <p class="text-xs text-amber-600 dark:text-amber-400 leading-relaxed">{{ $summary->why }}</p>
                    </div>
                    @endif
                    @if($summary->what_next)
                    <div class="rounded-xl bg-emerald-50 dark:bg-emerald-500/5 border border-emerald-100 dark:border-emerald-800/30 p-3.5">
                        <div class="flex items-center gap-1.5 mb-1.5">
                            <div class="size-1.5 rounded-full bg-emerald-400"></div>
                            <p class="text-xs font-semibold text-emerald-700 dark:text-emerald-300 uppercase tracking-wide">What's Next</p>
                        </div>
                        <p class="text-xs text-emerald-600 dark:text-emerald-400 leading-relaxed">{{ $summary->what_next }}</p>
                    </div>
                    @endif
                </div>
                @endif

                {{-- Footer: confidence + client version --}}
                <div class="flex flex-col sm:flex-row sm:items-center gap-3 pt-3 border-t border-gray-100 dark:border-gray-800">
                    @if($confidence)
                    <div class="flex items-center gap-2 flex-1">
                        <span class="text-xs text-gray-400 whitespace-nowrap">AI confidence</span>
                        <div class="flex-1 h-1.5 rounded-full bg-gray-100 dark:bg-gray-800 max-w-28">
                            <div class="h-1.5 rounded-full bg-{{ $confColor }}-400 transition-all" style="width: {{ $confidence }}%"></div>
                        </div>
                        <span class="text-xs font-semibold text-{{ $confColor }}-600 dark:text-{{ $confColor }}-400 tabular-nums">{{ $confidence }}%</span>
                    </div>
                    @endif

                    @if($summary->client_content && $summary->visible_to_client)
                    <div class="sm:ml-auto">
                        <details class="group">
                            <summary class="cursor-pointer text-xs text-gray-400 hover:text-brand-500 list-none flex items-center gap-1">
                                <svg class="size-3 transition-transform group-open:rotate-90" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg>
                                View client-facing version
                            </summary>
                            <div class="mt-2 rounded-lg border border-success-200 dark:border-success-800/30 bg-success-50/50 dark:bg-success-500/5 p-3">
                                <p class="text-xs font-medium text-success-700 dark:text-success-400 mb-1">Shared with client:</p>
                                <p class="text-xs text-gray-600 dark:text-gray-400 italic leading-relaxed">{{ $summary->client_content }}</p>
                            </div>
                        </details>
                    </div>
                    @endif
                </div>
            </div>
        </div>
        @endforeach
    </div>

    <div class="pt-2">{{ $summaries->links() }}</div>
    @endif

</div>
@endsection
